routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/bookmarks/grid', 'BookmarksController@grid');
Route::resource('/bookmarks', 'BookmarksController');
Route::get('/cms_apicustoms/grid', 'Cms_apicustomsController@grid');
Route::resource('/cms_apicustoms', 'Cms_apicustomsController');
Route::get('/cms_apikeys/grid', 'Cms_apikeysController@grid');
Route::resource('/cms_apikeys', 'Cms_apikeysController');
Route::get('/cms_dashboards/grid', 'Cms_dashboardsController@grid');
Route::resource('/cms_dashboards', 'Cms_dashboardsController');
Route::get('/cms_email_queues/grid', 'Cms_email_queuesController@grid');
Route::resource('/cms_email_queues', 'Cms_email_queuesController');
Route::get('/cms_email_templates/grid', 'Cms_email_templatesController@grid');
Route::resource('/cms_email_templates', 'Cms_email_templatesController');
Route::get('/cms_logs/grid', 'Cms_logsController@grid');
Route::resource('/cms_logs', 'Cms_logsController');
Route::get('/cms_menus/grid', 'Cms_menusController@grid');
Route::resource('/cms_menus', 'Cms_menusController');
Route::get('/cms_moduls/grid', 'Cms_modulsController@grid');
Route::resource('/cms_moduls', 'Cms_modulsController');
Route::get('/cms_notifications/grid', 'Cms_notificationsController@grid');
Route::resource('/cms_notifications', 'Cms_notificationsController');
Route::get('/cms_privileges/grid', 'Cms_privilegesController@grid');
Route::resource('/cms_privileges', 'Cms_privilegesController');
Route::get('/cms_privileges_roles/grid', 'Cms_privileges_rolesController@grid');
Route::resource('/cms_privileges_roles', 'Cms_privileges_rolesController');
Route::get('/cms_settings/grid', 'Cms_settingsController@grid');
Route::resource('/cms_settings', 'Cms_settingsController');
Route::get('/cms_statistic_components/grid', 'Cms_statistic_componentsController@grid');
Route::resource('/cms_statistic_components', 'Cms_statistic_componentsController');
Route::get('/cms_statistics/grid', 'Cms_statisticsController@grid');
Route::resource('/cms_statistics', 'Cms_statisticsController');
Route::get('/cms_users/grid', 'Cms_usersController@grid');
Route::resource('/cms_users', 'Cms_usersController');
Route::get('/dana_sosials/grid', 'Dana_sosialsController@grid');
Route::resource('/dana_sosials', 'Dana_sosialsController');
Route::get('/dana_sosial_details/grid', 'Dana_sosial_detailsController@grid');
Route::resource('/dana_sosial_details', 'Dana_sosial_detailsController');
Route::get('/gerejas/grid', 'GerejasController@grid');
Route::resource('/gerejas', 'GerejasController');
Route::get('/jadwal_kegiatans/grid', 'Jadwal_kegiatansController@grid');
Route::resource('/jadwal_kegiatans', 'Jadwal_kegiatansController');
Route::get('/jenis_ibadahs/grid', 'Jenis_ibadahsController@grid');
Route::resource('/jenis_ibadahs', 'Jenis_ibadahsController');
Route::get('/kategori_danasosials/grid', 'Kategori_danasosialsController@grid');
Route::resource('/kategori_danasosials', 'Kategori_danasosialsController');
Route::get('/kategori_gerejas/grid', 'Kategori_gerejasController@grid');
Route::resource('/kategori_gerejas', 'Kategori_gerejasController');
Route::get('/kidung_pujians/grid', 'Kidung_pujiansController@grid');
Route::resource('/kidung_pujians', 'Kidung_pujiansController');
Route::get('/kitabs/grid', 'KitabsController@grid');
Route::resource('/kitabs', 'KitabsController');
Route::get('/kitab_pujian_kategoris/grid', 'Kitab_pujian_kategorisController@grid');
Route::resource('/kitab_pujian_kategoris', 'Kitab_pujian_kategorisController');
Route::get('/konten_ibadahs/grid', 'Konten_ibadahsController@grid');
Route::resource('/konten_ibadahs', 'Konten_ibadahsController');
Route::get('/migrations/grid', 'MigrationsController@grid');
Route::resource('/migrations', 'MigrationsController');
Route::get('/pendeta/grid', 'PendetaController@grid');
Route::resource('/pendeta', 'PendetaController');
Route::get('/posts/grid', 'PostsController@grid');
Route::resource('/posts', 'PostsController');
Route::get('/profiles/grid', 'ProfilesController@grid');
Route::resource('/profiles', 'ProfilesController');
Route::get('/renungan_harians/grid', 'Renungan_hariansController@grid');
Route::resource('/renungan_harians', 'Renungan_hariansController');
Route::get('/roles/grid', 'RolesController@grid');
Route::resource('/roles', 'RolesController');
Route::get('/tata_ibadahs/grid', 'Tata_ibadahsController@grid');
Route::resource('/tata_ibadahs', 'Tata_ibadahsController');
Route::get('/users/grid', 'UsersController@grid');
Route::resource('/users', 'UsersController');
Route::get('/versi_kitab_pujians/grid', 'Versi_kitab_pujiansController@grid');
Route::resource('/versi_kitab_pujians', 'Versi_kitab_pujiansController');

app/Http/Controllers/PendetaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Pendetum;

use DB;

class PendetaController extends Controller
{
    //
    public function __construct()
    {
        //$this->middleware('auth');
    }


    public function index(Request $request)
	{
	    return view('pendeta.index', []);
	}

	public function create(Request $request)
	{
	    return view('pendeta.add', [
	        []
	    ]);
	}

	public function edit(Request $request, $id)
	{
		$pendetum = Pendetum::findOrFail($id);
	    return view('pendeta.add', [
	        'model' => $pendetum	    ]);
	}

	public function show(Request $request, $id)
	{
		$pendetum = Pendetum::findOrFail($id);
	    return view('pendeta.show', [
	        'model' => $pendetum	    ]);
	}

	public function grid(Request $request)
	{
		$len = $_GET['length'];
		$start = $_GET['start'];

		$select = "SELECT *,1,2 ";
		$presql = " FROM pendeta a ";
		if($_GET['search']['value']) {	
			$presql .= " WHERE nama_pendeta LIKE '%".$_GET['search']['value']."%' ";
		}
		
		$presql .= "  ";

		$sql = $select.$presql." LIMIT ".$start.",".$len;


		$qcount = DB::select("SELECT COUNT(a.id) c".$presql);
		//print_r($qcount);
		$count = $qcount[0]->c;

		$results = DB::select($sql);
		$ret = [];
		foreach ($results as $row) {
			$r = [];
			foreach ($row as $value) {
				$r[] = $value;
			}
			$ret[] = $r;
		}

		$ret['data'] = $ret;
		$ret['recordsTotal'] = $count;
		$ret['iTotalDisplayRecords'] = $count;

		$ret['recordsFiltered'] = count($ret);
		$ret['draw'] = $_GET['draw'];

		echo json_encode($ret);

	}


	public function update(Request $request) {
	    //
	    /*$this->validate($request, [
	        'name' => 'required|max:255',
	    ]);*/
		$pendetum = null;
		if($request->id > 0) { $pendetum = Pendetum::findOrFail($request->id); }
		else { 
			$pendetum = new Pendetum;
		}
	    

	    		
					    $pendetum->pendeta_id = $request->pendeta_id;
		
	    		
					    $pendetum->nama_pendeta = $request->nama_pendeta;
		
	    		
					    $pendetum->email = $request->email;
		
	    		
					    $pendetum->foto_gereja = $request->foto_gereja;
		
	    		
					    $pendetum->no_hp = $request->no_hp;
		
	    		
					    $pendetum->tahun_masuk = $request->tahun_masuk;
		
	    		
					    $pendetum->status = $request->status;
		
	    		
					    $pendetum->created_by = $request->created_by;
		
	    		
					    $pendetum->user_id = $request->user_id;
		
	    	    //$pendetum->user_id = $request->user()->id;
	    $pendetum->save();

	    return redirect('/pendeta');

	}

	public function store(Request $request)
	{
		return $this->update($request);
	}

	public function destroy(Request $request, $id) {
		
		$pendetum = Pendetum::findOrFail($id);

		$pendetum->delete();
		return "OK";
	    
	}

	
}

controllers/PendetaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pendeta;
use app\models\PendetaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PendetaController implements the CRUD actions for Pendeta model.
 */
class PendetaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pendeta models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PendetaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pendeta model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pendeta model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pendeta();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pendeta model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pendeta model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pendeta model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pendeta the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pendeta::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

resources/views/pendeta/add.blade.php
@extends('crudgenerator::layouts.master')

@section('content')


<h2 class="page-header">Pendetum</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        Add/Modify Pendetum    </div>

    <div class="panel-body">
                
        <form action="{{ url('/pendeta'.( isset($model) ? "/" . $model->id : "")) }}" method="POST" class="form-horizontal">
            {{ csrf_field() }}

            @if (isset($model))
                <input type="hidden" name="_method" value="PATCH">
            @endif


                                                <div class="form-group">
                <label for="pendeta_id" class="col-sm-3 control-label">Pendeta Id</label>
                <div class="col-sm-6">
                    <input type="text" name="pendeta_id" id="pendeta_id" class="form-control" value="{{$model['pendeta_id'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="nama_pendeta" class="col-sm-3 control-label">Nama Pendeta</label>
                <div class="col-sm-6">
                    <input type="text" name="nama_pendeta" id="nama_pendeta" class="form-control" value="{{$model['nama_pendeta'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Email</label>
                <div class="col-sm-6">
                    <input type="text" name="email" id="email" class="form-control" value="{{$model['email'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="foto_gereja" class="col-sm-3 control-label">Foto Gereja</label>
                <div class="col-sm-6">
                    <input type="text" name="foto_gereja" id="foto_gereja" class="form-control" value="{{$model['foto_gereja'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="no_hp" class="col-sm-3 control-label">No Hp</label>
                <div class="col-sm-6">
                    <input type="text" name="no_hp" id="no_hp" class="form-control" value="{{$model['no_hp'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="tahun_masuk" class="col-sm-3 control-label">Tahun Masuk</label>
                <div class="col-sm-6">
                    <input type="text" name="tahun_masuk" id="tahun_masuk" class="form-control" value="{{$model['tahun_masuk'] or ''}}">
                </div>
            </div>
                                                                                                            <div class="form-group">
                <label for="status" class="col-sm-3 control-label">Status</label>
                <div class="col-sm-2">
                    <input type="number" name="status" id="status" class="form-control" value="{{$model['status'] or ''}}">
                </div>
            </div>
                                                                                    <div class="form-group">
                <label for="created_by" class="col-sm-3 control-label">Created By</label>
                <div class="col-sm-6">
                    <input type="text" name="created_by" id="created_by" class="form-control" value="{{$model['created_by'] or ''}}">
                </div>
            </div>
                                                                                                <div class="form-group">
                <label for="user_id" class="col-sm-3 control-label">User Id</label>
                <div class="col-sm-6">
                    <input type="text" name="user_id" id="user_id" class="form-control" value="{{$model['user_id'] or ''}}">
                </div>
            </div>
                                                            
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-plus"></i> Save
                    </button> 
                    <a class="btn btn-default" href="{{ url('/pendeta') }}"><i class="glyphicon glyphicon-chevron-left"></i> Back</a>
                </div>
            </div>
        </form>

    </div>
</div>






@endsection

resources/views/pendeta/index.blade.php
@extends('crudgenerator::layouts.master')

@section('content')


<h2 class="page-header">{{ ucfirst('pendeta') }}</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        List of {{ ucfirst('pendeta') }}
    </div>

    <div class="panel-body">
        <div class="">
            <table class="table table-striped" id="thegrid">
              <thead>
                <tr>
                                        <th>Pendeta Id</th>
                                        <th>Nama Pendeta</th>
                                        <th>Email</th>
                                        <th>Foto Gereja</th>
                                        <th>No Hp</th>
                                        <th>Tahun Masuk</th>
                                        <th>Status</th>
                                        <th>Created By</th>
                                        <th>User Id</th>
                                        <th style="width:50px"></th>
                    <th style="width:50px"></th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
        </div>
        <a href="{{url('pendeta/create')}}" class="btn btn-primary" role="button">Add pendetum</a>
    </div>
</div>






@endsection



@section('scripts')
    <script type="text/javascript">
        var theGrid = null;
        $(document).ready(function(){
            theGrid = $('#thegrid').DataTable({
                "processing": true,
                "serverSide": true,
                "ordering": true,
                "responsive": true,
                "ajax": "{{url('pendeta/grid')}}",
                "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ url('/pendeta') }}/'+row[0]+'">'+data+'</a>';
                        },
                        "targets": 1
                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ url('/pendeta') }}/'+row[0]+'/edit" class="btn btn-default">Update</a>';
                        },
                        "targets": 9                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="#" onclick="return doDelete('+row[0]+')" class="btn btn-danger">Delete</a>';
                        },
                        "targets": 9+1
                    },
                ]
            });
        });
        function doDelete(id) {
            if(confirm('You really want to delete this record?')) {
               $.ajax({ url: '{{ url('/pendeta') }}/' + id, type: 'DELETE'}).success(function() {
                theGrid.ajax.reload();
               });
            }
            return false;
        }
    </script>
@endsection

resources/views/pendeta/show.blade.php
@extends('crudgenerator::layouts.master')

@section('content')



<h2 class="page-header">Pendetum</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        View Pendetum    </div>

    <div class="panel-body">
                

        <form action="{{ url('/pendeta') }}" method="POST" class="form-horizontal">


                
        <div class="form-group">
            <label for="pendeta_id" class="col-sm-3 control-label">Pendeta Id</label>
            <div class="col-sm-6">
                <input type="text" name="pendeta_id" id="pendeta_id" class="form-control" value="{{$model['pendeta_id'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="nama_pendeta" class="col-sm-3 control-label">Nama Pendeta</label>
            <div class="col-sm-6">
                <input type="text" name="nama_pendeta" id="nama_pendeta" class="form-control" value="{{$model['nama_pendeta'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="email" class="col-sm-3 control-label">Email</label>
            <div class="col-sm-6">
                <input type="text" name="email" id="email" class="form-control" value="{{$model['email'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="foto_gereja" class="col-sm-3 control-label">Foto Gereja</label>
            <div class="col-sm-6">
                <input type="text" name="foto_gereja" id="foto_gereja" class="form-control" value="{{$model['foto_gereja'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="no_hp" class="col-sm-3 control-label">No Hp</label>
            <div class="col-sm-6">
                <input type="text" name="no_hp" id="no_hp" class="form-control" value="{{$model['no_hp'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="tahun_masuk" class="col-sm-3 control-label">Tahun Masuk</label>
            <div class="col-sm-6">
                <input type="text" name="tahun_masuk" id="tahun_masuk" class="form-control" value="{{$model['tahun_masuk'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="status" class="col-sm-3 control-label">Status</label>
            <div class="col-sm-6">
                <input type="text" name="status" id="status" class="form-control" value="{{$model['status'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="created_by" class="col-sm-3 control-label">Created By</label>
            <div class="col-sm-6">
                <input type="text" name="created_by" id="created_by" class="form-control" value="{{$model['created_by'] or ''}}" readonly="readonly">
            </div>
        </div>
        
                
        <div class="form-group">
            <label for="user_id" class="col-sm-3 control-label">User Id</label>
            <div class="col-sm-6">
                <input type="text" name="user_id" id="user_id" class="form-control" value="{{$model['user_id'] or ''}}" readonly="readonly">
            </div>
        </div>
        
        
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <a class="btn btn-default" href="{{ url('/pendeta') }}"><i class="glyphicon glyphicon-chevron-left"></i> Back</a>
            </div>
        </div>


        </form>

    </div>
</div>







@endsection